umlConverter/converter/urls.py
from django.urls import path
from . import views


app_name = "converter"
urlpatterns = [
    path("", views.index, name="index"),
    path("canvas/", views.renderCanvas, name="canvas"),
    path("upload/", views.uploadTxtFile, name="upload")
]

umlConverter/umlConverter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("converter.urls")),
]

umlConverter/converter/models.py
from django.db import models 
from django.db.models import Model 

umlConverter/converter/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

umlConverter/converter/views.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse

# Create your views here.

def index(request):
    return render(request, "start/index.html", {
    })

def renderCanvas(request):
    if request.method == "POST":
        textFile =  request.FILES["txtfile"].read()
        print(textFile)
        #context = {"code":textFile}
        return render(request, "canvas/canvas.html", {"code":textFile})
    return render(request, "canvas/canvas.html")

def uploadTxtFile(request):
    return render(request,"start/index.html")

umlConverter/converter/templates/canvas/canvas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UML-Diagramm</title>
    {% load static %}
    <script src="{% static 'js/printOnCanvas.js' %}" defer data-code="{{ code }}"></script>
</head>
<body>
    <canvas id="myCanvas" width="1000" height="1000"></canvas>

</body>
</html>

umlConverter/converter/templates/start/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Document</title>
    {% load static %}
    <link rel="stylesheet" href="static/css/main.css" ></link>
</head>
<body>
    <div>
        <h1>Convert Java code to UML</h1>
        <form enctype="multipart/form-data" action="{% url 'converter:canvas' %}" method="post">
            {% csrf_token %}  
            <input type="file" name="txtfile" id="txtfile">
            <input type="submit">
        </form>
    </div>
</body>
</html>

umlConverter/converter/templates/success/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    
    <h1>Successful upload!</h1>

</body>
</html>